### PR TITLE
[WIP] parse html & complete URLs

### PR DESCRIPTION
**Pull request by jangernert**
This is a first try to implement #114 

It's behind the `parse-html` feature-gate and only implemented for atom right now. Would love to hear some general thoughts before proceeding @markpritchard

### CODE REVIEW

**Comment by markpritchard** [comment]
Hi @jangernert , thanks for the PR... but I'm wondering whether a different solution might work ? e.g. in https://github.com/feed-rs/feed-rs/issues/104#issuecomment-810057512 you mentioned that WebkitGTK can render content given a base URL?

It would be pretty simple to add the resolved XML-base at that node in the tree to the `Content` object. Does that work?

**Comment by jangernert** [comment]
I haven't actually tried it, but it should work.

**Comment by markpritchard** [comment]
OK, could you let me know if that works? If so, I'll extend the model to add xml-base to `Content`

**Comment by jangernert** [comment]
Yep, it works.

**Comment by markpritchard** [comment]
Great - checking the code, looks like I already implemented it for `Content`. The `src` field is populated using `xml:base` so I suspect this issue can be resolved?

**Comment by jangernert** [comment]
Is the `src` field ONLY populated by `xml:base` or is there a chance it could be something else? If that is not the case then this will work for me an the PR can be closed :)

**Comment by markpritchard** [comment]
Yes, for RSS1 and RSS2 its populated from `xml:base` :)

**Comment by markpritchard** [comment]
I'll close this PR, but feel free to open again or raise another issue if something isn't working.

**Pull request closed without merging**
