### PR TITLE
Added Eq and Hash basics for Feeds and Entries

### PR DESCRIPTION
**Pull request by eramoss**
implement basics too use feeds and entries in data structures like a hashMap

### CODE REVIEW

**Comment by markpritchard** [comment]
Thanks very much for the PR @eramoss ! 

Backward compatibility is really important for this library, and I'd want to make sure (particularly if we start serialising data) that the hash and eq contracts are stable over versions.

Would you mind adding some tests that assert the equality is maintained between a manually populated struct and a parsed instance? That way we can be sure that if new fields are added to the struct, we catch any differences in the behaviour of `Eq`.

**Comment by eramoss** [comment]
Of course! Sorry for not created it before, I was running creating a structure to analyze a feed and I needed this as faster as possible.

I only implemented traits on hand in Feed struct. In others structures only derivate it, so I created tests only for feed. If it has a problem be free to judge 😁

**Comment by markpritchard** [comment]
Hey @eramoss , thanks for adding the test cases. I think they highlight a bit of a problem conceptually with how RSS, Atom etc feeds work and this PR with respect to `eq`.

There is a concept of object graph equality i.e. does this `Feed` with a set of `Entry`s equal this other graph (like when we `assert_eq` in a test case. But a `Feed` is an entity that sits apart from its contained `Entry`s.

i.e. lets assume we have a `Feed` tracking arstechnica.com 's news. If you poll the feed regularly, you will receive different `Entry`s as its updated. But conceptually, its the same `Feed` - it just has different content (e.g. new articles).
Calling `eq` on a `Feed` and comparing its content (even just title) isn't stable, as all of that data is updatable by the publisher of the feed. For example, Ars Technica might change the title of the `Feed`, and with new `Entry`s , the published date will change too (breaking both `eq` and hash).

`feed-rs` tries to maintain the concept of a stable `id`. From the `Feed` doco:
```
    /// A unique identifier for this feed
    /// * Atom (required): Identifies the feed using a universally unique and permanent URI.
    /// * RSS doesn't require an ID so it is initialised to the hash of the first link or a UUID if not found
    pub id: String,
```
Atom mandates an ID (but of course, its the internet, so sometimes its not provided).
If we can't find an ID, we use the first link in the feed.

I suspect you are using these equality checks to understand if a feed has been updated? So I think we can solve your problem by just using the `id` of the `Feed` or `Entry` in your maps/sets and then implementing your own logic to handle updates/equality checks.

Please let me know if I've completely misunderstood the purpose of this PR :)

**Comment by markpritchard** [comment]
Will close this PR but please post any comments or questions if you have them.

**Pull request closed without merging**
