### PR TITLE
Treat top-level media elements as separate.

### PR DESCRIPTION
**Pull request by kevincox**
Previously all top-level elements would be included into a "default" group. However most feeds with top-level items that I have encountered treat top-level items as separate. One notable generator is Mastodon where multiple images in a post are included as top-level `<enclosure>` elements.

---

Note: I understand that this PR isn't "production-ready" but figured I would share it to show the change that has worked well for me. At the very least we will need docs updates and tests. This change may also need to be put behind a flag. If this change is wanted upstream I'll happily clean it up.

### CODE REVIEW

**Comment by markpritchard** [comment]
Thanks for preparing this @kevincox , would you mind including an example of a feed just so I can get a feel for the source data driving the change?

**Comment by kevincox** [comment]
Well the main mentioned example is mastodon. Unfortunatelly it seems like wordpress does the opposite, includes a ton of different resolutions and qualities as different top-level elements. I think the best option may be to update the PR to do this for `<enclosure>` but not the `media` types.

**Comment by kevincox** [comment]
It turns out that wordpress also references all images linked in the content as top-level `<media:content xmlns:media="http://search.yahoo.com/mrss/">`. I'm not sure these links are helpful but they definitely aren't different representations of the same media.

**Comment by kevincox** [comment]
I found a bug here. This makes different `itunes` entries be treated as separate. Probably it is best to treat all itunes item as a single media element independent of any other media element.

**Comment by markpritchard** [comment]
Hey @kevincox , just cleaning out old issues and figured I'd close this.
Feel free to re-open if you'd still like to work through this and get it merged
(perhaps it needs a different option to the parser to allow varying behaviour for example)

**Comment by kevincox** [comment]
I'm still running this patch and it seems better than the default. I would be interested in a way to move forward here. It is definitely hard because this space isn't well defined and feeds in the wild appear to do both behaviours. I see a few main options:

1. Keep the current state of assuming they are different things.
2. Switch to defaulting to merge top level things.
3. Add a pre-parse option to select between 1 and 2.
4. Add some metadata to the media structure to help the user decide. For example group top-level entries together but mark this group as top-level. Maybe also add a "recommendation" on how to handle it based on detected generator. This way users can make their own decision and maybe over time we can collect heuristics so that most users can get reasonable behaviour by default and just apply overrides in cases that are hurting them.

I think 4 is probably the best but it does have some downsides. Particularly complexity and maintenance. It is also somewhat unfortunate that if the user if the user ignores this attribute it basically falls back to 2 instead of defaulting to what the heuristic recommends.

**Pull request closed without merging**
