### PR TITLE
parser/atom: handle xml:base attribute on content

### LINKED ISSUE #211: feature: atom: handle xml:base attribute on content
atom content element define a optional xml:base attribute to `establishing the base URI (or IRI) for resolving any relative references found within the effective scope of the xml:base
   attribute.` from [rfc4287 section 2](https://datatracker.ietf.org/doc/html/rfc4287#section-2)

would you find acceptable to add a optional `base` field to [Entry](https://github.com/feed-rs/feed-rs/blob/890aeadc508c9228bcc01e25f0f861e32a68e741/feed-rs/src/model.rs#L233) ?

### PR DESCRIPTION
**Pull request by gleroi**
this add the base attribute found on ATOM entry.

fix #211

### CODE REVIEW

**Comment by markpritchard** [comment]
Thanks for the patch @gleroi ! 

Would you mind adding some tests to validate that we correctly populate the attribute and pass it through to the parsed representation?

A feed you are parsing works well as fixture data.

**Comment by gleroi** [comment]
yes, will do it as soon as possible

**Comment by gleroi** [comment]
i added a test to verify handle_entry extract the correct xml:base attribute.
i had to fix example_test_1 and example_test_3 as they had xml:base attribute on their content tag.

**Comment by markpritchard** [comment]
This looks great, thanks @gleroi !

**Pull request merged**
