### PR TITLE
handle date in rss1

### PR DESCRIPTION
**Pull request by basedtho**

### CODE REVIEW

**Comment by markpritchard** [comment]
Thanks for the PR @basedtho - do you have an example file with this extra element in it? Curious whether it should map on to published date, updated date etc given the RSS1 spec doesn't include this.

**Comment by basedtho** [comment]
it's right there, in your test data https://github.com/feed-rs/feed-rs/blob/master/feed-rs/fixture/rss_1.0_example_1.xml#L35

**Comment by markpritchard** [comment]
That is just a generic example I found on the internet ... I was wondering if you had a specific feed you were trying to parse that triggered this PR for you?

**Comment by basedtho** [comment]
@markpritchard http://rss.slashdot.org/Slashdot/slashdot

**Comment by markpritchard** [comment]
Neat, that is a great example. Thanks!

I can't merge your PR given it breaks CI but happy to grab Slashdot as an example and extend the parser.

**Comment by markpritchard** [comment]
Interestingly the `date` element is namespaced into DublinCore - I've been wanting to add support for namespaces for a little while now so will go ahead and do that + pick up dates for RSS1.

**Comment by basedtho** [comment]
it works as it is with my addition, maybe namespaces are already implemented?

**Comment by markpritchard** [comment]
They are just ignored at the moment (which is actually a bug) ... so this
is a good driver to implement namespace filtering and then add support for
the DublinCore standard namespaces.

**Comment by basedtho** [comment]
it's been a while, so i don't really remember and can't answer a question i have - could this be the reason why dates can't be parsed in, say, reddit feeds? here is one example https://www.reddit.com/r/rust/.rss - all articles have the same date of jan 1

**Comment by markpritchard** [comment]
I wonder if Reddit had a bug they subsequently fixed ... there was another
report of Reddit's feed being broken, but I can't reproduce it. I added a
test case for Reddit anyway, just to make sure changes don't impact it in
the future.

The original issue you reported was that feed-rs doesn't handle the date
field on RSS1 items ... but its not in the RSS1 namespace, its actually in
Dublin Core.

I do have an MR I'm working on to add support for elements in common
namespaces so this should be fixed too (I'll release it as 0.3.0).

**Comment by basedtho** [comment]
github atom feeds don't have dates either
https://github.com/feed-rs/feed-rs/releases.atom

**Comment by markpritchard** [comment]
Remarkable - its a mandatory element. Looks like I need to crack on with #25 to pick up namespaces, and implement something sensible for this case too.

Thanks for the extra example!

**Comment by markpritchard** [comment]
Fixed in #52 , let me know if you have any questions or issues @basedtho

**Pull request closed without merging**
