### PR TITLE
Implements support for Media RSS

### LINKED ISSUE #68: Implement media spec support
The library is great!

I think for me the only missing piece is support for media namespaces handling.
The spec is here: https://www.rssboard.org/media-rss

Sadly lots of RSS/Atom feeds is using it, including Youtube atom feeds: https://www.youtube.com/feeds/videos.xml?user=kkszysiu

I think having support for it would be great.
I will try to introduce a PR that adds at least basic implementation in the comming days.

### PR DESCRIPTION
**Pull request by markpritchard**
Closes #68

### CODE REVIEW

**Comment by evilpie** [comment]
Thanks very cool! Personally I would like a design that wasn't that close to the media spec.

**Comment by markpritchard** [comment]
What were your concerns with the media spec?

Personally, I found the need to navigate around the tree remembering context (this element is inherited unless overridden etc) quite painful - I think feed-rs should take care of things like that. Similar to how feed-rs creates unique IDs, tries to fix dates etc.

**Comment by evilpie** [comment]
I have the feeling a lot of the features in the media spec aren't actually used in practice. For example I doubt `<media:price>` is used anywhere. Sadly it's kind of hard to find a good list of example feeds for this.

I actually hadn't realized how weird the nesting can get before ...

> Optional Elements
>The following elements are optional and may appear as sub-elements of `<channel>`, `<item>`, `<media:content>` and/or `<media:group>`.

**Comment by evilpie** [comment]
Things like `<media:rating>` don't seem that well specified either. I think all these schemes in the spec are just fake.

**Comment by markpritchard** [comment]
I was thinking about implementing support for the key elements, and skipping over the poorly specified elements (that are just strings, with no pointers to actual specs or enumerated values). feed-rs does this for other schemas too (dropping elements that are rarely used etc).

**Comment by markpritchard** [comment]
This is an initial release of MediaRSS support with test data for Atom only ... but its worth getting it out there for testing and feedback.

**Pull request merged**
